### ISSUE TITLE
Use projected volumes for automount configmaps/secrets when they use the same mount path

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#1021]
### Description
Currently, attempting to start a workspace in a namespace with automount configmaps/secrets that share the same mountpath results in the workspace failing to start, with message like 

> Failed to process automount resources: auto-mounted volumes from configmap 'configmap-1' and configmap 'configmap-2' have the same mount path

Instead, DWO could mount both configmaps using a projected volume.

**Comment by max-cx** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-4195
