### ISSUE TITLE
Use Che Code in test cases instead of Theia

### ISSUE THREAD

**Issue by AObuchow** [devfile/devworkspace-operator#1028]
Now that Theia will no longer be officially supported, the test data we use should aim to use Che Code instead of Theia. 

@nickboldt has identified the following test data as needing to be updated:

* [ ]  `pkg/library/flatten/testdata/container-contributions/`
* [ ]  `pkg/library/flatten/testdata/implicit-container-contributions/`
* [ ]  `pkg/library/flatten/testdata/implicit-spec-contributions/`
* [ ]  `pkg/library/flatten/testdata/k8s-ref/`
* [ ]  `pkg/library/flatten/testdata/spec-contributions/`
* [ ]  `pkg/library/lifecycle/testdata/postStart/`

**Comment by AObuchow** [comment]
After some thought, I don't think it's necessary to remove the test data listed in the issue description: the tests are still valid even if Theia is no longer officially supported. 

However, we should probably remove the `theia-latest` sample, as the URL it's using for the theia editor devfile is down, and I can't seem to find a replacement URL.

**Comment by nickboldt** [comment]
given use of theia was...
*  [deprecated in DS 3.5](https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.5/html-single/release_notes_and_known_issues/index#deprecated-functionality-crw-4113) (Che 7.60), and
* [removed/sunset in DS 3.6](https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.6/html-single/release_notes_and_known_issues/index#removed-functionality-crw-3663) (Che 7.64),  and that 
* the current release is 7.70...

I would argue that having any mention / use of theia in tests/code is no longer recommended. Updating the tests to focus on vscode would be better than keeping them and having them still mention theia, which is no longer a supported editor in Che.
