### ISSUE TITLE
Proxy not injected to project-clone container

### ISSUE THREAD

**Issue by gbonnefille** [devfile/devworkspace-operator#1066]
### Description
In a corporate env, the git clone failed.

### How To Reproduce
I configured our proxy in a dwoc.yaml.

I used https://github.com/devfile/devworkspace-operator/blob/main/samples/code-latest.yaml

### Expected behavior
A successful git clone.

**Comment by gbonnefille** [comment]
I can confirm the other containers have proxy correctly set in environment.

**Comment by gbonnefille** [comment]
Seems to be a known limitation: https://github.com/devfile/devworkspace-operator/blob/4ea3d5cd8ef0622cf7883b62e7b782941f174b04/pkg/library/projects/clone.go#L73

**Comment by amisevsk** [comment]
@gbonnefille Good catch -- this was a TODO that slipped through the cracks at some point.
