### ISSUE TITLE
Add automount annotation to allow configuring access mode for mounted configmaps

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#1072]
### Description
One use case for automounted configmap is mounting an executable script that can be run from within the container. This is generally possible in Kubernetes, by mounting the configmap with execute permissions (see: https://github.com/kubernetes/kubernetes/issues/71356), but the DevWorkspace Operator prevents this use case by always mounting configmaps with `0644` permissions. 

The DevWorkspace Operator should have an additional automount annotation to configure the access mode for the mounted resource.

### Additional context
This would be very useful for configuring in-container initialization; for example, Eclipse Che documents using an `init-truststore.sh` script to enable Gradle artifact repositories via automount volumes: https://www.eclipse.org/che/docs/stable/end-user-guide/enabling-gradle-artifact-repositories/

**Comment by max-cx** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-4197
