### ISSUE TITLE
Use consistent capitalization in error messages 

### ISSUE THREAD

**Issue by AObuchow** [devfile/devworkspace-operator#1092]
https://github.com/devfile/devworkspace-operator/pull/1064 refactored the way errors were propagated in the devworkspace-controller, and highlighted the fact that some error messages in DWO [start with a lower case letter](https://github.com/devfile/devworkspace-operator/pull/1064/files#diff-bfb432d51dee16f88d16a491fd7b8f24fbe2d56bc53d1036fee90e6fa27e0354R127) while [others start with a capital letter](https://github.com/devfile/devworkspace-operator/pull/1064/files#diff-bfb432d51dee16f88d16a491fd7b8f24fbe2d56bc53d1036fee90e6fa27e0354R88).

It would be nice to make the capitalization of error messages consistent, as they can be shown to the user in cases where the workspace startup fails.

Some things to consider:
- Do we want DW error & warning status messages to always start with a lower case letter, or upper case?
- Some error messages get [concatenated with another error message](https://github.com/devfile/devworkspace-operator/pull/1064/files#diff-05e72230161a4d41c5a27fb453041c78839c193a9ddcb5066b1cb62c5a399529R133) to provide some context, so it's not just a matter of changing all error messages to start with an upper or lower case letter.
  -   Maybe the functions set the workspace status messages (e.g. [this one for failing workspaces](https://github.com/devfile/devworkspace-operator/pull/1064/files#diff-05e72230161a4d41c5a27fb453041c78839c193a9ddcb5066b1cb62c5a399529R549)) should automatically capitalize the first letter of the workspace status message. This way, we could more easily enforce the standard of all error messages starting with a lowercase letter while ensuring user-facing error messages start with an uppercase letter.

**Comment by Horiodino** [comment]
hey @AObuchow If no one else is currently working on this issue, I would like to take it on. Please let me know if it's available for me to handle.

**Comment by AObuchow** [comment]
@Horiodino no one is currently working on this issue, I'd be happy to have you work on it :)
