### ISSUE TITLE
Provide workspaces.annotations field in DWOC for all devworkspaces

### ISSUE THREAD

**Issue by dkwon17** [devfile/devworkspace-operator#1270]
### Description

There is no way to add annotations to all workspaces in the DWOC

My proposal is to add `config.workspaces.annotations` field in DWOC that allows setting annotations to add to a devworkspace's pod.

### Additional context

This feature would help implement:
* https://issues.redhat.com/browse/CRW-6550
* https://github.com/eclipse-che/che/issues/22809

**Comment by AObuchow** [comment]
Resolved in https://github.com/devfile/devworkspace-operator/pull/1271
