### ISSUE TITLE
Output stdout & stderr of postStart events to Kubernetes event 

### ISSUE THREAD

**Issue by AObuchow** [devfile/devworkspace-operator#1324]
### Description
https://github.com/devfile/devworkspace-operator/pull/1081 added support for multiple postStart events. Their stdout and stderr are grouped together and redirected to `/tmp/poststart-stdout.txt` & `/tmp/poststart-stderr.txt` respectively. 

Additionally, if multiple postStart events are used, the postStart hook will succeed as long as the last postStart event succeeds.

However, as a side effect, if the last (or only) postStart event fails, the stdout and stderr of the postStart event will not be propagated to the Kubernetes event on the cluster. Since a postStart hook failure will cause the pod to terminate, it's impossible to SSH/exec into the workspace container and read the output of  `/tmp/poststart-stdout.txt` & `/tmp/poststart-stderr.txt`. This makes debugging failing postStart events difficult.

It'd be nice to somehow propagated the stdout & stderr of postStart events to the Kubernetes event, while also logging them into `/tmp/poststart-stdout.txt` & `/tmp/poststart-stderr.txt` .

### Additional context
[Downstream issue](https://issues.redhat.com/browse/CRW-6580)

**Comment by AObuchow** [comment]
It seems that an [update](https://github.com/kubernetes/kubernetes/issues/119541) that appeared in Kubernetes 1.26 now prevents the output of Kubernetes Lifecycle hooks from being displayed in the FailedPostStartHook event. This was done for security reasons to prevent any sensitive information from the postStart event from leaking.

Since this is outside of the control of DWO, I'm unfortunately going to close this issue.

**Comment by AObuchow** [comment]
Removing the v0.31.x milestone as this was closed as a WON'T FIX.

**Comment by muja** [comment]
So what options or workarounds are there for debugging failing poststart events?

The only one I'm aware of is:

```yaml
command: ["/bin/sh", "-c", "( ORIGINAL_COMMAND >/tmp/command1-stdout 2>/tmp/command1-stderr; echo $? > /tmp/command1-status ) || true"]
```

**Comment by rohanKanojia** [comment]
@muja : Hello, I had recently added support for debugging failing postStart events by adding this annotation (see [docs](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#debugging-a-failing-workspace)):
```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: your-workspace-name
  annotations:
    controller.devfile.io/debug-start: "true"
```

You can add this annotation to your workspace metadata and then create it, it won't get scaled down immediately after failure. The poststart failures would be trapped with debug sleep; you can exec into the workpace pod and check `/tmp/poststart-stdout.txt` or `/tmp/poststart-stderr.txt` to inspect why it failed.
