### ISSUE TITLE
Update environment variables

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#160]
### Is your enhancement related to a problem? Please describe.
Lot of environment variables defined in containers are using `CHE_` prefix.
It shouldn't as it is agnostic of Che.

### Describe the solution you'd like
I would get a clear mapping between old and new names

Also, some environment variables could be available through files
For example k8s stores some config in `/var/run/secrets/kubernetes.io/serviceaccount` file

`CHE_MACHINE_TOKEN` (or others) could be a candidate to use files instead of ENV variables ? like `/var/run/secrets/devfile.io/machine-token`

| ENV NAME | Replacement |
| --------------- |  --------------- |
| CHE_API | N/A |
| CHE_API_INTERNAL | N/A |
| CHE_WORKSPACE_ID | N/A (end user info) |
| CHE_MACHINE_TOKEN | N/A |
| CHE_WORKSPACE_TELEMETRY_BACKEND_PORT | (not defined per che server) CHE_WORKSPACE_TELEMETRY_BACKEND_PORT (not yet implemented). It's needed to take a look if Devfile 2.x allows plugins to bring their env vars into containers, like it's supported in [plugin.meta.yaml](https://github.com/redhat-developer/che-workspace-telemetry-woopra-backend/blob/300c83d80a52f8fe51cc1992b71d8ebb9d6b7a2c/meta.yaml#L12) |
| CHE_MACHINE_NAME | DEV_WORKSPACE_COMPONENT_NAME |
| CHE_PROJECTS_ROOT | COMPONENT_PROJECTS_ROOT or PROJECTS_ROOT|

Non CHE_ variables
| ENV NAME | Replacement |
| --------------- |  --------------- |
| NO_PROXY | NO_PROXY |
| HTTP_PROXY | HTTP_PROXY |
| HTTPS_PROXY | HTTPS_PROXY |

Che/Theia is expecting as well a
| ENV NAME | Replacement |
| --------------- |  --------------- |
| PRODUCT_JSON | config map for json |

**Comment by amisevsk** [comment]
All `CHE_` prefixed variables are used since that's what che-rest-apis and che-theia expect (afaik). If all external components and plugins support another way to define these values, we can use them but I think changing these will require updating che-theia, etc.

**Comment by sleshchenko** [comment]
CHE_WORKSPACE_TELEMETRY_BACKEND_PORT depends on devfile/api side: https://github.com/devfile/api/issues/149

PRODUCT_JSON is something Che should care about.

Proxy settings also will handled out of the current PR issue.

We still need to provision `DEVWORKSPACE_COMPONENT_NAME` (https://github.com/eclipse-che/che-theia/blob/e47ba31982d6b41fd5e93dcf1392b372ae2fae81/extensions/eclipse-che-theia-plugin-remote/src/node/che-content-aware-utils.ts)
We need to recheck PROJECTS_ROOT but it seems to be in place https://github.com/devfile/devworkspace-operator/blob/e0e3b622dfd0ed1cb81b5a91866e8fe6cb23e791/pkg/library/constants/constants.go

Everything else should be already done.

**Comment by sleshchenko** [comment]
Closing this issue since I don't see whatelse can be done on DWO side.
If there is any work left - please create dedicated issues.
