### ISSUE TITLE
workspace routings objects name

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#161]
### Is your enhancement related to a problem? Please describe.
workspaces resources are available with devworkspaces
but workspace routings are with workspaceroutings

### Describe the solution you'd like
if instead of using Workspace we use DevWorkspace
we should have WorkspaceRoutings renamed to DevWorkspaceRoutings

**Comment by amisevsk** [comment]
I don't think it matters too much what internal bookkeeping structs are called, but at this point it's hard to change names since they're used in the web terminal operator.

**Comment by benoitf** [comment]
can be filtered using
```
$ kubectl get WorkspaceRoutings --all-namespaces --selector="controller.devfile.io/workspace_id=<id>"
```
