### ISSUE TITLE
Links to external resources from a devworkspace

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#162]
### Is your enhancement related to a problem? Please describe.
When we've a dev workspace, we can ask resources like with

```
$ kubectl get devworkspaces --all-namespaces
```

but runtime information is missing as well as the components from these objects.
That information is stored in other custom resources

### Describe the solution you'd like
It would be nice that from a DevWorkspace we could have pointers to the runtime info custom resources and component custom resources

There is like a pattern-rule with workspace-id suffix but would be more convenient to know the related source names from the DevWorkspace resource

### According to 2nd October call:
We could use labels for all workspace related objects with an identifier of the dev workspace.

It may be simpler to use workspace name but not workspaceId that we have since namespace/name fully identifies devworkspace CR instance.

Most of workspace-related objects are cluster-scoped (so namespace label seems to be redundant), but some of them could be cluster-scoped, like OpenShift Oauth client. Then to grab all workspace-related objects we need to have namespace label as well.

Example of label: `io.devfile.dev_workspace.name` + `io.devfile.dev_workspace.namespace`

Che-Theia knows the identifier of the dev workspace and then will be able to do the queries.

\* name/namespace could be combined in one label if it makes sense + `namespace format/name format` satisfies label value format, like we won't exceed the maximum length.
Having different labels for name and namespace could be more straightforward since namespace is optional when you do a namespace-scoped query (which should 100% case of Che Theia).

**Comment by amisevsk** [comment]
The additional components are internal on purpose; runtime information is stored in the configmap defined for each workspace for now, and mounted in the `che-rest-apis` container.

**Comment by benoitf** [comment]
we could use labels with identifier of the dev workspace 
example of label:`io.devfile.devworkspace.name`

Che-Theia know the identifier of the dev workspace and then will be able to do the queries

need to check with cluster admin roles/namespaces

**Comment by benoitf** [comment]
I've moved comment to the description

**Comment by sleshchenko** [comment]
Closing it, what may be considered as left: link to flattened devfile from devworkspace status. But we agreed we won't add it until we see necessity and a dedicated issue should exist on devfile/api side.
