### ISSUE TITLE
Grab registries URLs from a workspace

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#163]
### Is your enhancement related to a problem? Please describe.
Che-theia (or other workspaces) may want to know which registries (like plug-in and/or devfile) were used to create this workspace. (For example for che-theia it is to list all other plug-ins and the one who are enabled)

There is a config map of the devworkspace controller but workspaces won't have the permission to read from there.

### Describe the solution you'd like
Registries URLs should be available inside DevWorkspace annotation or config maps information or mounted information file in `/var/run/secrets/devfile.io/` that can be used to grab these URLs or anything else

**Comment by sleshchenko** [comment]
As we discussed on the latest call, probably it should be stored in the configmap that theia can access directly or via mount file or env var. We assume that plugin registries could be provision from two places: 
- config map that manages DevWorkspace Controller and it provision values from the configuration it has. It's like default per cluster plugin registry;
- user is able to enable additional plugin registries via their preferences configmap;

* supporting multiple plugin registries is not implemented yet and there are still some questions how we should implement it on devworkspace controller.

**Comment by sleshchenko** [comment]
DevWorkspace Operator is not in charge of managing registries and providing their URLs.
Instead, a new issue is created to support a common way to mount configmaps, secrets into devworkspace:
- Provide a mechanism to automount configmap/secret into devworkspaces https://github.com/devfile/devworkspace-operator/issues/384

And Che has an issue to get an agreement how Che would propagate their configs:
- How to handle configuration spread across DWO, WTO and DWCO https://github.com/eclipse/che/issues/19326
