### ISSUE TITLE
Complete endpoints implementations needed for Theia plugins

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#184]
It's needed to complete endpoints implementations needed for Theia plugins:
Theia defines https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/java11/0.63.0a/meta.yaml protocol, discoverable, type, path which have a bit different location in devfile 2.0 format

**Comment by davidfestal** [comment]
On branch `use-v1alpha2-and-new-attributes` I'm working on the the start of this issue:
- Using the new endpoint validated fields: exposure, path, protocol, secure, instead of the old corresponding attributes.

**Comment by sleshchenko** [comment]
The thing that Devfile 2.0 is missing - a unique host. I've created the corresponding issue on devfile/api side. https://github.com/devfile/api/issues/230

**Comment by sleshchenko** [comment]
It believe it can be safety closed now.
Devfile API and DevWorkspace Che Operator has their issues to support uniqueHost
