### ISSUE TITLE
Remove configmap from operator

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#191]
### Is your enhancement related to a problem? Please describe.
Currently, the devworkspace operator relies on a configmap to define a few options (default routingClass, etc.). However, operators as managed by OLM don't come with configmaps, and instead we create a configmap on cluster during startup as a way of manually configuring the operator after the fact. 

### Describe the solution you'd like
We should remove configmap functionality as its generally not used for operators. Instead configuration should be defined in a standard way, e.g. by [OLM descriptors](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#7-number)

### Additional context
This issue was created for a [TODO](https://github.com/devfile/devworkspace-operator/pull/187/files#diff-05e72230161a4d41c5a27fb453041c78839c193a9ddcb5066b1cb62c5a399529R314) added in PR #187

**Comment by davidfestal** [comment]
> We should remove configmap functionality as its generally not used for operators. Instead configuration should be defined in a standard way, e.g. by OLM descriptors

I'm not sure I understand your point here. Aren't OLM descriptors used to specify the UI for presenting / changing Custom Resources in the OperatorHub console. I don't see how you plan to use them to set controller settings...

**Comment by amisevsk** [comment]
> Aren't OLM descriptors used to specify the UI for presenting / changing Custom Resources in the OperatorHub console. I don't see how you plan to use them to set controller settings...

Maybe I misinterpreted the purpose of OLM descriptors, but even so, configuring an operator via a configmap does not seem to be a standard flow (happy to be wrong, though).
