### ISSUE TITLE
Investigate how reducing containers number influences workspace-startup time

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#218]
This issue is about investigating how reducing containers number influences workspace-startup time
As the object of investigation can be chosen any language pack devfile, like Java, Go...

As an example Java Maven https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-maven/devfile.yaml
Currently, if you run it on OSIO you'll get the following images:
```
init containers
"quay.io/eclipse/che-theia-endpoint-runtime-binary:7.22.0"
"quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"

authentication
"quay.io/eclipse/che-jwtproxy:0.10.0"
// are run for every Theia based containers
"quay.io/eclipse/che-theia:7.22.0"
"quay.io/eclipse/che-machine-exec:7.22.0"
// language specific sidecar, runs vsx + has preinstalled tools for them
"quay.io/eclipse/che-sidecar-java:11-86274e3"
// container designed for user to use terminal and execute commands
"quay.io/eclipse/che-java11-maven:7.22.0"
// OSIO specific plugin-container provisioned in every workspace
"quay.io/eclipse/che-workspace-telemetry-woopra-plugin:latest"
```
According to https://docs.google.com/document/d/1V8RA6_wEd20vTRKL60yPXmRIN8A_lo5ps8mb0T9FUwY/edit#heading=h.s3u51mcvho3h each image takes 2 additional seconds even if it's already cached on the node.

It's needed to investigate what here can be merged and how much it speeds up workspace start-up, like: plugin-artifact-broker can be removed if we download VSX into plugin sider on the build. The same about Endpoint runtime binary.
Che Theia can be merged with Che Machine Exec.

Then we could go in different ways:
Prepare language-specific flat all-on-one image, like Theia + java plugin (user still is able to add additional images if needed)
or run Theia + prepare language specific flat tooling image (user still is able to add additional images if needed)
See https://github.com/devfile/devworkspace-operator/issues/209#issuecomment-738086637

I'm not sure what we can do with JWTProxy + Telemetry sidecars.

**Comment by amisevsk** [comment]
I've done an artificial test that basically confirms our expectations: I started DevWorkspaces with a varying number of containers (the workspace consists of che-theia, che-machine-exec, and [1-10] plain containers) and plotted how long workspace start takes, averaged over ten starts. We can see adding containers linearly increases the time for workspace startup (at a rate of around 1.1s per additional container):

![Average workspace startup time (ms) - (minikube)](https://user-images.githubusercontent.com/16168279/101935112-8b27ff00-3bac-11eb-84fb-019bc9aaefa3.png)
![Workspace startup time (ms) by step - (minikube)](https://user-images.githubusercontent.com/16168279/101935115-8bc09580-3bac-11eb-9251-8c5ee6104ce7.png)
![Time waiting on deployment vs number of containers](https://user-images.githubusercontent.com/16168279/101935114-8bc09580-3bac-11eb-9d0a-2586c26a1eb0.png)

**Comment by amisevsk** [comment]
To try it yourself, I created a tiny repo: https://github.com/amisevsk/workspace-timing

**Comment by amisevsk** [comment]
Testing with minikube and `IfNotPresent` pullPolicy results in similar behaviour, but faster (around 600ms per additional container, average 7s for 1 additional container to a max of 14s for 10 containers.

**Comment by amisevsk** [comment]
Closing this issue as I think we've got a pretty good idea of this effect -- ~1 second per container on start, assuming each container is cached.
