### ISSUE TITLE
Investigate devfile flattening + devworkspace startup workflow

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#227]
Investigate devfile flattening + devworkspace startup workflow.

During preparing a proposal, it's needed to take into account 
Plugins in Devfile 2.0 https://docs.google.com/presentation/d/17qAUiTY752INugy3iajb8ujku8eJXWmOnPF1SaTBxMA/edit#slide=id.g7862af9181_0_0
Investigating faster workspace startup https://github.com/devfile/devworkspace-operator/issues/209
Git Clone First https://github.com/devfile/devworkspace-operator/issues/205

**Comment by amisevsk** [comment]
This one can probably be closed in favor of other issues we've created since. Flattening is more-or-less implemented as of https://github.com/devfile/devworkspace-operator/pull/269
