### ISSUE TITLE
Implement plugin flattening for DevWorkspaces

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#249]
## Description:
- [x] Implement basic plugins support (https://github.com/devfile/devworkspace-operator/pull/240)
- [x] Support defaulting Web Terminal workspaces (add default component) (https://github.com/devfile/devworkspace-operator/pull/263)
- [x] Support plugins specified by id

**Comment by sleshchenko** [comment]
The support for parents is moved to a dedicated issue.
I don't think it's important for Devfile 2.0 + Che or WTO.

**Comment by sleshchenko** [comment]
To avoid this issue be a long-long story, plugins with URI is moved to a dedicated issue as well https://github.com/devfile/devworkspace-operator/issues/266
