### ISSUE TITLE
Should we have a flattening subcontroller?

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#262]
## Description

As we implement the full devfile/api plugins functionality, we should consider whether the flattening process should be separated out into a subcontroller, similar to what we had for Component subresources 

### Pros:
- Cache results so that we don't need to flatten on every reconcile loop
    - This could be especially useful as we start making http requests to flatten (plugin specified by URI)
- Expose flattened devfile through status of the subresource

### Cons:
- Caching may not be that useful, if a) kubernetes references to devworkspacetemplates are expected to be the main use case and b) the flatten step is fast enough
- More complexity; another fixed internal API we have to deal with.
- We can expose the flattened devfile in other, potentially more useful ways

**Comment by davidfestal** [comment]
I tend to lean towards creating a dedicated sub-resource + a sub-controller. This might provide more flexibility about *when* we do the flattening (possibly do it *before* the workspace is started). But I understand the cons as well and this might not be worth it.

**Comment by amisevsk** [comment]
A concern here is that the subresource would have the CRD
```yaml
spec: 
  template:
    &devfilev1alpha.DevWorkspaceTemplateSpec
status:
  flattened:
    &devfilev1alpha2.DevWorkspaceTemplateSpec
```
which means that any breaking change in devfile/api is a breaking change in the subresource.

**Comment by amisevsk** [comment]
Since it's been over a year and we haven't felt the need for this, I'm closing the issue for now. It can be reopened if this becomes an issue down the line.
