### ISSUE TITLE
Set up release for DevWorkspace Operator

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#283]
Since Che 7.27 is going to have initial integration with DWO https://github.com/eclipse/che/milestone/136

It's needed to set up release, which will:
- create v0.$VERSION.x branch, like v0.1.x
- build and push released version image
- regenerate default templates with the released image, https://github.com/devfile/devworkspace-operator/blob/main/deploy/generate-deployment.sh#L73
- set version in VERSION or somewhere else
- commit made changes
- do git tag (deployment files should be used from there)

- bump version in main branch  to v0.${VERSION+1}.0, like v0.2.0

**Comment by nickboldt** [comment]
Please provide more details:
* how to build nightly
* how to build release
* image name & repo in quay to which to publish image (is this already set up or does it need to be done?)
* bump version in main branch in what file(s)? a VERSION file or something else?
* multiarch considerations - do we need to worry about z, p, aarch, arm at this stage, or punt that down the line to phase 4?
* is the version pattern for image tags, or for CRs? Do you expect that there'll be a new release every 3 weeks, and the CR version will also be incremented for each release?

**Comment by amisevsk** [comment]
>Please provide more details:
>
>* how to build nightly, how to build release
>    -  given there are [2 dockerfiles which both produce an image based on a ubi8 container](https://github.com/devfile/devworkspace-operator/tree/main/build), why do we need two different builder images? Could we remove the alpine-builder-based Dockerfile and rename rhel.Dockerfile to Dockerfile for simplicity?
>

Looking at the dockerfiles, yeah we can probably just use the rhel one for everything

>* image name & repo in quay to which to publish image (is this already set up or does it need to be done?)
>    - something new under https://quay.io/organization/devfile ?
>

We've currently got [quay.io/devfile/devworkspace-controller](https://quay.io/repository/devfile/devworkspace-controller) receiving nightlies, though the naming might be a bit strange (the repo was created before we renamed to `devworkspace-operator`)

>* bump version in main branch in what file(s)? a VERSION file or something else?
>    - https://github.com/devfile/devworkspace-operator/blob/main/version/version.go ?
>    - should that version be aligned to the CR version, or are they completely different?
>

No sure what to do here; afaik we don't have a VERSION file, as go versions are defined by git tags. We should decide a branching strategy (probably what WTO uses)

>* multiarch considerations - do we need to worry about z, p, aarch, arm at this stage, or punt that down the line to phase 4, and only worry about multiarch in terms of CRW productization for now
>    - operator must be rhel-based, like the Che operator, with no strange rpm or other dependencies which don't exist / don't work on other arches
>

I think we're putting off multi-arch for now. There's a WTO jira for it. Dependencies-wise I don't think we've got any problems (WTO is basically a DWO release from 8 months ago)

>* is the version pattern for image tags, or for CRs? Do you expect that there'll be a new release every 3 weeks, and the CR version will also be incremented for each release?

CR versions are staying `v1alpha1` for as long as I can keep them. Changing CR versions is a big deal and requires us to implement conversion webhooks. I think for operator versions (tags in the repo), `v0.x.y` is ideal to avoid issue with Go

**Comment by nickboldt** [comment]
Is this issue complete?

**Comment by mkuznyetsov** [comment]
Release workflow is located at https://github.com/devfile/devworkspace-operator/actions/workflows/release.yml
