### ISSUE TITLE
makefile should check if kustomize is installed

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#294]
After pulling recent changes and performing `$ make install`
I got

```
deploy/generate-deployment.sh: line 128: kustomize: command not found
make: *** [generate_deployment] Error 127
```

it should check if the tool exists and for example on macos propose to do: `brew install kustomize`

**Comment by amisevsk** [comment]
It should already do this, from the `_kustomize` rule:
```
_kustomize:
ifeq (, $(shell which kustomize))
	@{ \
	set -e ;\
	KUSTOMIZE_GEN_TMP_DIR=$$(mktemp -d) ;\
	cd $$KUSTOMIZE_GEN_TMP_DIR ;\
	go mod init tmp ;\
	GOFLAGS="" go get sigs.k8s.io/kustomize/kustomize/v3@v3.5.4 ;\
	rm -rf $$KUSTOMIZE_GEN_TMP_DIR ;\
	}
KUSTOMIZE=$(GOBIN)/kustomize
else
KUSTOMIZE=$(shell which kustomize)
endif
```
I suspect the issue may be in how `$PATH` is configured on macOS -- it should include `$GOPATH/bin`

**Comment by amisevsk** [comment]
Fixed by https://github.com/devfile/devworkspace-operator/pull/324
