### ISSUE TITLE
Separate workspace routing into a separate library

### ISSUE THREAD

**Issue by metlos** [devfile/devworkspace-operator#298]
Because the controllers/workspacerouting  package is reused in 2 operators now, it would be good if it was separated out of the main devworkspace-operator code into a separate codebase.

This would improve the code isolation and chances of introducing dependencies on code/configuration that is not common to all the operators that use the workspace routing code.

In particular, it would make it possible to not rely on `config.ControllerConfig` in the workspace routing codepaths, because the configuration mechanism differs between the operators.

**Comment by amisevsk** [comment]
I agree that the code used in the workspaceRouting controller shouldn't depend on any mutable state from elsewhere (i.e. no config settings), but would prefer to keep it in this codebase so that we can share constants, attributes, annotations, etc.
