### ISSUE TITLE
DevWorkspace controller is OOMKilled with just one DevWorkspace existing

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#313]
I face from time to time when DevWorkspace operator is OOMKilled and the last time I face it after I created one DevWorkspace which was only on the cluster.

So, we should better understand how much resources do you need and how devworkspaces number influences it.

**Comment by sleshchenko** [comment]
quick fix is merged into v0.2.0 and backported to v0.1.x, but the proper solution is not planned yet

**Comment by amisevsk** [comment]
From some testing with the metrics PR (https://github.com/devfile/devworkspace-operator/pull/405), it seems like our current settings are sufficient to avoid OOMKilled, but I'm leaving this issue open for now as we previously weren't setting a memory/cpu limit for the webhooks deployment (see https://github.com/devfile/devworkspace-operator/pull/410) and that needs to be tested as well.
