### ISSUE TITLE
[WTO] DevWorkspace can't start after controller is reinstalled

### ISSUE THREAD

**Issue by tinakurian** [devfile/devworkspace-operator#327]
Steps to reproduce: 

1. install WTO with operatorhub
2. uinstall WTO with operatorhub
3. install WTO with operatorhub
4. try to create terminal, it hangs due DevWorkspace SA webhook server issue

**Comment by sleshchenko** [comment]
Duplicates https://issues.redhat.com/browse/WTO-77
