### ISSUE TITLE
Investigate integration with devfile/api library functions

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#328]
### Description

We've thus far been writing library functions as required in `pkg/library`. However, the devfile/api side also has a library package which duplicates some work. We should investigate integration between the two, ideally porting common functionality into the devfile/api or using existing functionality where appropriate. 

### Additional Info
Related to https://github.com/eclipse/che/issues/17667, which aged out of date.

**Comment by sleshchenko** [comment]
there is no any plan regard integrating DWO with library ATM
