### ISSUE TITLE
Limit privileges of DevWorkspace serviceaccount

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#342]
### Description
I came across a [half-written TODO](https://github.com/devfile/devworkspace-operator/blob/735cf60315c1add99945840b3fe1913eca3e793e/controllers/workspace/provision/rbac.go#L36) today (I wrote it -- it's my bad):

> // TODO: The rolebindings here are created namespace-wide; find a way to limit this, given that each workspace

The idea here was to restrict the devworkspace SA to only have control over workspace-related objects (and avoid a potential -- but slight -- privilege escalation).

Should we still proceed with trying to do this? Currently, being able to start workspaces gives the user the privileges to CRUD `devworkspaces` and `devworkspacetemplates`, create permissions on `pods/exec`, and view permissions on all pods/deployments/replicasets/devworkspaceroutings in the devworkspace's namespace.

**Comment by amisevsk** [comment]
Completed as part of https://github.com/devfile/devworkspace-operator/pull/954

**Comment by AObuchow** [comment]
@amisevsk since https://github.com/devfile/devworkspace-operator/pull/954 resolved this, which was part of 0.18.x can I put this in the 0.18.0 milestone?

**Comment by amisevsk** [comment]
Good catch, added to 0.18 milestone
