### ISSUE TITLE
Get rid of CHE_API and CHE_API_EXTERNAL

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#344]
The devWorkspace is still adding CHE_API, CHE_API_INTERNAL and CHE_API_EXTERNAL env variables

https://github.com/devfile/devworkspace-operator/search?q=DefaultApiEndpoint

as the rest sidecar has been dropped, it should have been deleted as well.

**Comment by benoitf** [comment]
maybe the whole https://github.com/devfile/devworkspace-operator/blob/0322bc38a6d798eb02a4bf927c714964c1f88c61/pkg/library/shim/component.go could be removed

**Comment by sleshchenko** [comment]
Fixed by https://github.com/devfile/devworkspace-operator/pull/347
