### ISSUE TITLE
Users may need an ability to override resources for project clone

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#397]
Initially, the project clone failed due OOMKilled. 300Mi for memory fixes the issue but I wonder if bigger projects require more memory for cloning.

So, in this issue it's needed to investigate how clonned repo size influences memory consumption and if it's significant - we probably should implement an ability to override project clone memory, via devfile attribute or any other way.

**Comment by amisevsk** [comment]
This has been handled in other issues, e.g. https://github.com/devfile/devworkspace-operator/issues/739
