### ISSUE TITLE
Figure out how DevWorkspace operator / webhooks server responds to heavy load

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#398]
### Description

Since the DevWorkspace operator adds webhooks for `pods/exec`, we need to stress-test the webhooks server (and to a lesser extent, the controller itself) to get a sense of what effect deploying this to a big cluster would have. This is crucial since every time the webhooks server crashes, all `pods/exec` requests are blocked until it comes back up.

1. What memory/cpu limit is required by the webhooks server to allow it to handle a given amount of `pods/exec` requests on a cluster?
2. How is throughput affected when the webhooks server is under load? Are we delaying every `pods/exec` significantly when we're under load?

Part of the difficulty in testing this is getting a reasonable estimate of how many requests we should actually expect.

**Comment by sleshchenko** [comment]
that's done.
metrics can be found at https://drive.google.com/drive/folders/1KP7_PEeLVy8Hv_gPlRiNFXQVecyPlsX9?usp=sharing
