### ISSUE TITLE
Adapt to ideUrl -> mainUrl renaming

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#399]
DWO, devWorkspace client and dashboard should be adapted to ideUrl -> mainUrl renaming

**Comment by JPinkney** [comment]
devworkspace-client PR: https://github.com/che-incubator/devworkspace-client/pull/22
dashboard PR: https://github.com/eclipse-che/che-dashboard/pull/232
devworkspace operator PR: https://github.com/devfile/devworkspace-operator/pull/423

**Comment by sleshchenko** [comment]
All components now should be adapted to ideUrl -> mainUrl renaming.
But there is one item missing: make endpoints define `type: main` instead of `type: ide`. See https://github.com/devfile/devworkspace-operator/pull/423/files#r630758675
I assume this changes needs to be done on DWO and plugin registry side.

**Comment by sleshchenko** [comment]
- [ ] Plugin registry PR https://github.com/eclipse-che/che-plugin-registry/pull/963

**Comment by sleshchenko** [comment]
All expected changes are moved to use main endpoint type.
