### ISSUE TITLE
Update tags used for images (`:ci` instead of `:next`) 

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#401]
### Description

Currently, we use the following tags for DWO-related images:
- `next` is used for per-commit builds (i.e. on the day of release, `next` becomes currently released version)
- `vX.Y.Z` is used for released versions
- `latest` is not used and has never been pushed

We should review this and define a scheme going forward. Note that Eclipse Che has a similar issue open (https://github.com/eclipse/che/issues/19291) that suggests using `ci` as the per-commit build tag -- I'm not a huge fan of that approach since to me `ci` suggests that it's an image *used for* CI rather than *produced by* CI.

**Comment by nickboldt** [comment]
if not `ci` then is `nightly` better ?

**Comment by benoitf** [comment]
nightly is not a good choice when it's not done at night but After every commit

And `ci` I don't know what it means. Like is it used by CI jobs ? When is it done ?

**Comment by nickboldt** [comment]
Instead of saying no to everything I suggest, could you suggest something better?

**Comment by benoitf** [comment]
> Instead of saying no to everything I suggest, could you suggest something better?

I like `next` (but I already said that I think) because it let me think it's what is coming up next

Also in chectl there are two channels: `stable` and `next` 

so if I use chectl with `next` channel, and that images are using `next` tag I'm not lost

**Comment by JPinkney** [comment]
What if we just used the branch name as the tag? So `quay.io/devfile/devworkspace-controller:main` would just be the image created by the latest changes in main

**Comment by nickboldt** [comment]
once all repos have migrated to main (instead of master) then yeah, that could work too. similar to downstream convention of having a floating tag for the stable branch, you could also have a v0.3.x or v0.4.x label for builds from the stable branch (to differentiate builds tagged from the main branch)

**Comment by benoitf** [comment]
I prefer `main` or `next` over `ci`
we're using `main` for plugin registry artifacts coming : https://che-plugin-registry-main.surge.sh/v3/plugins/

It was to have consistency with `next` channel of`chectl` but it might be changed here as well

**Comment by sleshchenko** [comment]
Seems DWO has nothing to do with it
