### ISSUE TITLE
Should Kubernetes references in plugin/parent resolve across the entire cluster?

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#403]
### Description

Currently, when using a name/namespace pair to reference a DWT in a plugin or parent, the DevWorkspace controller will resolve that reference regardless of the namespace. This means that one could read DevWorkspaceTemplates in another namespace, even if they do not have permissions to read that namespace, provided they know the name/namespace pair.

Should we restrict plugin/parent references to a single namespace? If we do decide to restrict in this way, what's the point of having a namespace field at all?

The current approach allows for easier management of parents/plugins (you can just keep them all in one namespace). Removing this capability would mean that every namespace would need any parents/plugin DWTs the DevWorkspace intends to use. On the other hand, allowing DWTs to come from any namespace is a (minor) privilege escalation.

**Comment by amisevsk** [comment]
Note: restricting `namespace` for plugins would mean the proposed solution for having WTO depend on DWO would no longer work (since WTO would be deploying DWTs to a specific namespace for use by all Web Terminals)

**Comment by sleshchenko** [comment]
> Note: restricting namespace for plugins would mean the proposed solution for having WTO depend on DWO would no longer work (since WTO would be deploying DWTs to a specific namespace for use by all Web Terminals)

It can be configured. With OpenShift CSVs will get allowed the current namespace + openshift-operators.

**Comment by sleshchenko** [comment]
As we agreed on DevWorkspace Cabal, it's not good to make DWT read-only available for all by default, and actually does not have permissions to create private one.
At first step we could allow openshift-operators by default to expose WTO's DWT.
Later we can introduce:
1. CRD that could define DWT in namespace as exposed.
2. Simpler - annotations on DWT with rules in which namespaces it should be available. By default - only the current one,
