### ISSUE TITLE
Update devfile 2.1 API in the operator

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#406]
For now, the devworkspace operator is consuming devfile 2.1 API specified at
https://github.com/devfile/devworkspace-operator/blob/main/Makefile#L26

which is https://github.com/devfile/api/commit/1f335562c475972132851c68227dd36558317bb3

I'm interested in having global attributes changes
https://github.com/devfile/api/tree/ff3c01bf82927e2936d66f31b93e9463f9be25b3

so if you could please bump to a more recent 2.1 specification

**Comment by amisevsk** [comment]
Fixed by https://github.com/devfile/devworkspace-operator/pull/409
