### ISSUE TITLE
Implement variable substitution

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#408]
### Description

As of commit https://github.com/devfile/api/commit/ff3c01bf82927e2936d66f31b93e9463f9be25b3, the devfile 2.0 spec includes support for variable substitution (see issue https://github.com/devfile/api/issues/239). The DevWorkspace Operator needs to be updated to process variable substitutions via the devfile library once a DevWorkspace has been flattened.

**Comment by sleshchenko** [comment]
is implemented in https://github.com/devfile/devworkspace-operator/pull/409
