### ISSUE TITLE
Cannot start failed workspaces

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#413]
### Description
The controller will stop (i.e. set `.spec.started=false`) any workspace that has `.status.phase=failed`. Since starting a workspace does not clear the phase/conditions, it is impossible to start a workspace once it has entered the Failed state since it just hits the same condition and is stopped again.

We can work around this in multiple ways:
- We can use the `Failed` phase only to mark a running workspace that still has to be stopped, and use the `Stopped` phase once the stop has been completed (failure reason can still be shown in the INFO field).
- We can introduce a "Failing" state or similar, that is used to mark a workspace that has failed and should be stopped
- We can clear a DevWorkspace's `.status.phase` and `.status.conditions` when `.spec.started` is changed from false to true in a webhook

**Comment by benoitf** [comment]
Also how can we grab logs of the pod (or one container of the pod) when it's stopping the workspace that has a failed status ?

**Comment by amisevsk** [comment]
@benoitf That's another issue I encountered when I ran into this one (and probably deserves its own issue). My plan was to support an annotation or attribute on DevWorkspaces to direct the controller to not scale deployments to zero on failure (similar to how we have a "debug start" option in Che itself) -- WDYT?

Created https://github.com/devfile/devworkspace-operator/issues/418 for follow-up

**Comment by benoitf** [comment]
@amisevsk yes I agree that it's a separate issue, thanks for the follow-up issue (and annotation's idea to control if scale to zero or not)
