### ISSUE TITLE
use tag image in Makefile when tagging the release

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#415]
If I checkout `v0.2.3` [[1]](https://github.com/devfile/devworkspace-operator/blob/v0.2.3/Makefile#L21) or `v0.3.2` [[2]](https://github.com/devfile/devworkspace-operator/blob/v0.3.2/Makefile#L21) tag of devworkspace operator, the Makefile still reference `:next` tag so `make install` command doesn't work out of the box

I think release process [[3]](https://github.com/devfile/devworkspace-operator/commit/af1b6bd88986cce2a7983e069070d4570994a378) should also update Makefile when cutting a release

**Comment by sleshchenko** [comment]
it should be fixed already, at least 0.7.2 seems to have the right values https://github.com/devfile/devworkspace-operator/blob/v0.7.2/Makefile
