### ISSUE TITLE
Add annotation/attribute to disable scale-to-zero on DevWorkspace failure

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#418]
### Description

When a DevWorkspace enters a failed state, the deployment for it is scaled to zero. This means that any logs that could be used to debug a `CrashLoopBackoff` are unavailable. 

It would be great to have an annotation or attribute we can apply to DevWorkspaces to disable the scale-to-zero behavior and allow users to view logs when required.

**Comment by sleshchenko** [comment]
:+1: And dashboard can expose this feature to a user with `Open In Verbose Mode`
