### ISSUE TITLE
Add an ability to generate some secrets for workspace

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#434]
### Is your enhancement related to a problem? Please describe.
Currently, the reconcile loop works in the following way:
1. evaluate objects according to status of the devfile (no communication with cluster)
2. flush them onto cluster

And if the devfile is not changed then the first part should always have the same result.
We already have some piece which must be regenerated for each workspace, or even on each workspace start - it's cookies_secret for oauth-proxy container https://github.com/che-incubator/che-workspace-operator/blob/master/pkg/controller/workspacerouting/solvers/oauth_proxy_container.go#L85

Also, oauthclient is comming.

### Describe the solution 1
1. evaluate objects according to status of the devfile. Generate some values with rand (no communication with cluster)
2. flush them onto cluster, but before flushing - override randomized values with cluster ones

### Describe the solution 2
1. evaluate objects according to status of the devfile. Generate some values with rand if missing on the cluster or fill in with the already existing
2. flush them onto cluster

**Comment by sleshchenko** [comment]
At this point we don't have a use-case for it since openshift oauth routing is removed.
Good proposal Josh prepared is located at https://github.com/devfile/devworkspace-operator/pull/68/files and is about having secret with fixed name - secret-store, that will be managed by DWO and component will be able to set key there without value, while value is going to be generated by DWO before flushing on the cluster.

**Comment by amisevsk** [comment]
Closing as out of date.
