### ISSUE TITLE
Add an ability to select secret/config maps to mount for particular devworkspace/component

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#435]
There is an issue in which scope we add an ability to define secret/configmap that will be bound (as file or env var) for all components of all devworkspaces in the current namespace.

This issue is about adding more flexibility to cover cases when like maven setting should be bound only to maven component.

May be related issue on devfile API side: Support externally-defined volume components https://github.com/devfile/api/issues/374

**Comment by amisevsk** [comment]
Closing as stale -- if a need arises for this we can implement it later but as far as I know there's no downside to giving maven settings to non-maven containers.
