### ISSUE TITLE
devworkspace fails to start when init container exited but the error is not helpful for end-users

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#442]
Starting a devWorkspace, I've the error

```
NAMESPACE         NAME               DEVWORKSPACE ID             PHASE    INFO
opentlc-mgr-che   spring-petclinic   workspacec4b044cd3dfa4a26   Failed   Init Container project-clone has state CrashLoopBackOff
```

It would be nice to have a better error reporting for end-users

The root cause, after grabbing logs is:
```
2021/06/03 13:57:09 Read DevWorkspace at /devworkspace-metadata/flattened.devworkspace.yaml
2021/06/03 13:57:09 Cloning project spring-petclinic to spring-petclinic
2021/06/03 13:57:09 failed to clone project spring-petclinic: project checkoutFrom refers to non-existing remote
```

so it could be nice to have the error reported directly instead of seeing that a container is in CrashLoopBack state

**Comment by sleshchenko** [comment]
Well, I would distinct two issues:
- devworkspace with invalid devfile (non-existing remote referenced, non-existing component referenced from command) should fail earlier and report issue better. Probably we should do it with validating webhooks;
- DWO should somehow report crashed container logs to user;

**Comment by sleshchenko** [comment]
Closing this issue since two improvements are done and you won't face the same behavior.
