### ISSUE TITLE
Project clone should respect workspace CAs

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#455]
Project clone should respect workspace CAs.
It's critical for airgap mode of CRW, where devfile registry serves projects as zip archives though self-signed https. Note: as alternative we could use internal network which is HTTP, but then we have another issue that NetworkPolicies should be configured in the corresponding way.

**Comment by amisevsk** [comment]
This feature is supported by automounting secrets/configmaps and the (current) project clone container. To add a self-signed cert to your DevWorkspace, the process is

1. Get the certificate (e.g. for testing with the devfile registry and crc, get the crc ingress operator cert)
2. Create a secret from the cert:
    ```
    kubectl create secret generic selfsigned-cert-secret \
      --from-file=cluster.crt=/path/to/cert/from/step/one
    ```
3. Annotate the secret to be mounted to DevWorkspaces:
    ```json
    kubectl patch secret selfsigned-cert-secret --type merge -p \
      '{
        "metadata": {
          "labels": {
            "controller.devfile.io/mount-to-devworkspace": "true"
          }, 
          "annotations": {
            "controller.devfile.io/mount-path": "/usr/local/share/ca-certificates/"
          }
        }
      }'
    ```
