### ISSUE TITLE
Add a role to be able to create, list and delete secrets by a namespace user

### ISSUE THREAD

**Issue by vinokurig** [devfile/devworkspace-operator#483]
Need to add a role and bind it to a namespace user, to be able to create, list and delete secrets. See: https://github.com/eclipse-che/che-server/pull/44

**Comment by sleshchenko** [comment]
So, changes are made but not merged since we agreed it's not the way to go https://github.com/devfile/devworkspace-operator/pull/489

So, closing this issue and please create a new one when it'll be known which way we'll go for credentials store.
