### ISSUE TITLE
Workspace PVCs are never updated and are not removed from the cluster

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#488]
### Description
The DevWorkspace PVC (`claim-devworkspace`) is not updated on reconcile cycles, so once it exists its configuration is static. In addition, it is not removed from a namespace when all DevWorkspaces are deleted and must be manually cleaned up.

**Comment by AObuchow** [comment]
PVC cleanup is closed by https://github.com/devfile/devworkspace-operator/pull/834. Additional work regarding resizing the common PVC (i.e. modifying the PVC configuration) should be tracked in a new issue.
