### ISSUE TITLE
Figure out how to support using personal access tokens in project clone

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#506]
### Description

The project-clone init container supports automounting SSH keys to interact with private git repos. We also need to support setting a password, e.g. using [`personal access tokens`](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token).

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/devfile/devworkspace-operator/pull/564
