### ISSUE TITLE
Remove icon field from bundle manifests

### ISSUE THREAD

**Issue by JPinkney** [devfile/devworkspace-operator#507]
Currently if you create a devworkspace index and apply it to the cluster you'll get:
![Screenshot from 2021-07-23 10-46-56](https://user-images.githubusercontent.com/8839537/126799469-61a49203-3f2d-443d-b27d-c4c037c91525.png)
and
![Screenshot from 2021-07-23 10-47-28](https://user-images.githubusercontent.com/8839537/126799466-885aa5f7-12f6-4cc1-8add-b02a10e89407.png)

My guess is that this is happening because the icon is empty in the manifests: https://github.com/devfile/devworkspace-operator/blob/main/deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml#L63. We can probably do what web terminal does and remove the icon field and it will display the default icon instead

**Comment by sleshchenko** [comment]
fixed https://github.com/devfile/devworkspace-operator/pull/521
