### ISSUE TITLE
Add support for devfile 2.0 variables

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#508]
### Description

The devfile 2.0 spec includes global variables, which define key-value pairs, e.g.
```
variables:
  my-var: "some value"
```
These variables can be referenced in non-key string fields within the devfile using `{{my-var}}` to template different versions of a devfile by setting only the variable field.

We should add support for this in DWO.

See issue https://github.com/devfile/api/issues/239 and PR https://github.com/devfile/api/pull/352 for details.

**Comment by sleshchenko** [comment]
is implemented with https://github.com/devfile/devworkspace-operator/pull/509

**Comment by sleshchenko** [comment]
duplicates https://github.com/devfile/devworkspace-operator/issues/408
