### ISSUE TITLE
Switch devworkspace operator e2e tests to OpenShift 4.8

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#535]
Switch devworkspace operator e2e tests to OpenShift 4.8

**Comment by dmytro-ndp** [comment]
@sleshchenko: I have found "**area/qe**" label in this issue, which is expected to be in issues inside https://github.dev/eclipse/che
Did you stop using https://github.dev/eclipse/che as an issue tracker?

**Comment by sleshchenko** [comment]
@dmytro-ndp DevWorkspace operator keeps the issues common enough for DWO, which does not have a relation to Che.
DevWorkspace + Che issues live in eclipse/che repo

**Comment by sleshchenko** [comment]
done in https://github.com/openshift/release/pull/21509
