### ISSUE TITLE
Documentation for DevWorkpace Operator specific features

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#577]
DevWorkspace provides a few features on the top of devfile:
- mounting secrets/config maps into devworkspace;
- configuring image pull secrets;
- configuring git https tokens;
- configuring devworkspace on namespace level;
- annotate the devworkspace to debug startup;

Features list is growing on the way we're moving forward integration with Che, and the only place where these features are described - go code.
It's needed to start DevWorkspace Operator Documentation to describe such features, which will be the source of truth for Che and other dependent projects.

From docs team:
>  a documentation built using Antora and following modular docs guidelines, like what we have for devfile or che-docs would be perfect and much appreciated in the eventuality of a future downstream reuse.
> that a new docs project would be best to start using the toolchain we  already have in place for Che and devfile docs

**Comment by JPinkney** [comment]
Initial devworkspace configuration documentation branch is: https://github.com/devfile/devworkspace-operator-docs/tree/configuration-documentation
