### ISSUE TITLE
Allow to disable project-clone component

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#606]
Each workspace has now a lot of init-containers, each one performing its own action.

One problem is that these actions are run sequentially so if for example I have two init containers with each task taking 10seconds it will result in having 20s delay (without counting pull/start of each container)

So it might be interesting if the editor could specify its own 'all-in-one init container' and then disabling the one provided by devWorkspace operator (project-clone)

To disable it, it could be an annotation on the DevWorkspaceTemplate

**Comment by sleshchenko** [comment]
closing in favor of https://github.com/devfile/devworkspace-operator/issues/607
