### ISSUE TITLE
Support Pod tolerations for DevWorkspace Pods

### ISSUE THREAD

**Issue by metlos** [devfile/devworkspace-operator#614]
### Description
To support node selection for workspace pods, it would be great if we supported pod tolerations and node selector for DevWorkspace pods.

It would be best if this was a noop but we need to investigate if the same can be done on namespace level - e.g. by labeling namespaces such that addmission controllers can select the nodes automatically, see https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector

**Comment by sleshchenko** [comment]
As far I as understand @l0rd will provide a better requirement for this feature, like should it be defined on namespace object/on a specific workspace level.

**Comment by l0rd** [comment]
I have looked at past issues and here is the [original](https://github.com/eclipse/che/issues/14562) where it's mentioned that a central config is required first. NodeSelector per workspace was considered a successive iteration. 

I also found a customer request:
> node selector would be great to have. If that can be defined in dev file e.g, that would be best. 
So being able to specify that at workspace level is important too (I don't think that we should do that at devfile spec level though as that would make the devfile less portable).

Summing it up:
- Higher priority: being able to have current, global, che-server configuration in devworkpace world too
- Lower priority: being able to specify NodeSelector at the workspace level

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by amisevsk** [comment]
Supporting this makes sense as a part of the main Devfile API; I've created https://github.com/devfile/api/issues/689 and will follow up.

**Comment by skabashnyuk** [comment]
Now pod teleration look like this 
```
# Optionally configures tolerations for workspace Pod. Format is a string representing a JSON Array of taint tolerations,
# or `NULL` to disable it. The objects contained in the array have to follow the
# link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#toleration-v1-core[toleration v1 core specifications].
# Example: `[{"effect":"NoExecute","key":"aNodeTaint","operator":"Equal","value":"aValue"}]`
che.workspace.pod.tolerations_json=NULL
```
 @amisevsk can you tell us how this config should look like so devworkspace controller can understand it?

**Comment by amisevsk** [comment]
We had a discussion in a devfile/api call today, and it sounds like we want to hold off on setting per-workspace tolerations and node selectors for now. As a result, it's not fully clear how this will be implemented on the DWO side for the time being, though it will likely be as a global config option.

Formatting-wise, what's in Che would work. The initial proposal (https://github.com/devfile/devworkspace-operator/pull/681) uses pod tolerations matching the k8s object (we literally deserialize into `[]corev1.PodTolerations`). For node selectors, it's just a `map[string]string`.

**Comment by amisevsk** [comment]
PR https://github.com/devfile/devworkspace-operator/pull/696 adds support for setting tolerations and node selectors at a namespace level. @skabashnyuk would it be possible to make Che apply the appropriate annotations when syncing a user's namespace?

**Comment by skabashnyuk** [comment]
@amisevsk I think yes. https://github.com/eclipse/che/issues/20884
