### ISSUE TITLE
DWO should track workspaces that go from `Running` to `Starting`

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#618]
### Description
The DevWorkspace operator currently makes no note of workspaces that go from the `Running` phase to the `Starting` phase. This could be useful information in diagnosing certain issues (e.g. a pod that is continually being updated). In addition, not detecting this event can skew metrics for successful startups, as each time a pod restarts it is counted as a successful start (though with start duration based of when the workspace was initially started).

One factor that should be considered is that sometimes these restarts are expected (if e.g. the user updates their running workspace to use a new plugin).

### Additional context
In load testing DWO, I noticed that some pods were continually being recreated, which suggests some sort of issue but isn't tracked by DWO.

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?
