### ISSUE TITLE
Theia-next sample stuck on waiting for editor to start

### ISSUE THREAD

**Issue by JPinkney** [devfile/devworkspace-operator#621]
### Description

As of today, the theia-next sample is failing to start. The devworkspace permanently gets stuck in:
```
NAME           DEVWORKSPACE ID             PHASE      INFO
theia-latest   workspacec9f477e6402546ea   Starting   Waiting for editor to start
```
and the theia-next main route gets a 503 response with the health check. I've tried rolling back the [theia version to 7.36.1](https://gist.githubusercontent.com/JPinkney/3b81a789fd21754579660c42411fe820/raw/1b8cf4add7593b38b0e44982443f61d2e72c79e1/test.yaml) and have tried reverting back to an earlier version of the devworkspace operator with no success. It's not exactly clear if this is a devworkspace issue or a che issue so I've filed it here for now

### How To Reproduce

```
make docker install
oc apply -f samples/theia-next.yaml
```

### Expected behavior

mainUrl is assigned and we can open devworkspace

**Comment by sleshchenko** [comment]
If it's about samples DWO has, https://github.com/devfile/devworkspace-operator/pull/622 should fix it.
