### ISSUE TITLE
Mount volumes to all containers by defining it in a DevWorkspaceTemplate

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#628]
### Description
Allow DevWorkspaceTemplate to notify the controller to mount a given volumePath to all containers

### Additional context
use-case: As editors could run inside the user containers, there is a need to be able to execute the container from this volume.
But we can't require to have all devfiles adding a volume that they don't know about.

So I would know if I could use some annotations to notify that I want that a volume could be added in all containers.

### Note
It would be fine to only mount the volume in the first available container or a container being annotated

**Comment by amisevsk** [comment]
Likely superceded by https://github.com/devfile/devworkspace-operator/issues/656 -- please reopen if this is needed independently from the other issue.
