### ISSUE TITLE
Document Annotations handled by DevWorkspace

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#657]
### Description
Hello, looking at https://github.com/devfile/devworkspace-operator#annotations
I see that there is only one annotation being supported.

But when I discussed other items, in issue https://github.com/devfile/devworkspace-operator/issues/630#issuecomment-933458347 there are other annotations

It would be nice to document them as it seems there are many there: https://github.com/devfile/devworkspace-operator/blob/5e82c76619c8ea10459d8310df6d7c015e08b416/pkg/constants/metadata.go

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?
