### ISSUE TITLE
Create a test plan for DWO

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#666]
### Description
We should create a test plan covering DWO usecases that should be tested for each release.

**Comment by JPinkney** [comment]
The basic test scenario I followed for 0.10 and 0.11 is:
1. Create theia-next sample
2. Ensure that the devworkspace starts and you can open theia
3. Delete the devworkspace and ensure that the cleanup pod runs successfully and doesn't error
4. Repeat steps 1-3 with theia-latest sample

Once those are done then:
1. Install Web Terminal Operator
2. Verify that a terminal can be created with a admin user
3. Verify that the terminal works for the admin
4. Verify that a terminal can be created with a normal user
5. Verify that the terminal works for a normal user

We should probably also check that everything in [additional configuration](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.md) can be added and configured

**Comment by ibuziuk** [comment]
In the next sprint the target is to move the documented test plan to Polarioin

**Comment by amisevsk** [comment]
I believe this issue can be closed, finally :D

cc: @musienko-maxim
