### ISSUE TITLE
Check that DWO is compatible with network-isolated clusters

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#668]
### Description
We need to make sure that DWO functions correctly in an airgapped cluster and document any issues or additional requirements that are needed.

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by ibuziuk** [comment]
issues related to this spike:
- https://github.com/devfile/devworkspace-operator/issues/665
- https://issues.redhat.com/browse/CRW-2473

**Comment by ibuziuk** [comment]
@rhopp @dmytro-ndp folks, could you please point to the instructions that QA are using for the air-gap / network-isolated clusters setup? The plan is that @ScrewTSW is going to own the verification of the DevWorkspace running in this environment

**Comment by dmytro-ndp** [comment]
@ibuziuk: there is a set of scripts created by Radim and Flavius, which we are using downstream to setup OCP for CRW testing:
1) deploy disconnected OCP: https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/blob/master/jobs/CodereadyWorkspaces/Disconnected/orchestrator.Jenkinsfile
2) to setup image mirroring and install CRW in there: https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/blob/master/jobs/CodereadyWorkspaces/Disconnected/installCRW.Jenkinsfile

Here the document prepared by Flavius: https://docs.google.com/document/d/1ZbzhoUYhV7gbZVJkX5o0kId8VOw1TNuWso89PNAP8uw/edit?usp=sharing

**Comment by ibuziuk** [comment]
standalone DWO has been checked against airgap cluster.
Now we need to verify Eclipse Che 7.42.0 with the DevWorkspace enabled on the same environment

**Comment by l0rd** [comment]
Closing as this should have been verified now

**Comment by ibuziuk** [comment]
@ScrewTSW @musienko-maxim @dmytro-ndp folks, reopening this issue for clarification. 
I'm not sure if this flow has been verified e2e with the recent fixes on the operator side.

**Comment by ibuziuk** [comment]
Closing this issue after discussion and opening https://github.com/eclipse/che/issues/21205 for e2e latest Eclipse Che verification in the air-gap mode.
