### ISSUE TITLE
Enable proxy support for DevWorkspaces

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#678]
### Description
Currently, DevWorkspaces have no way to specify proxy settings, so built-in containers such as project-clone will fail to clone projects if running behind a proxy. We need to define a way to specify proxy settings and figure out how to propagate these down to the workspace pods.

### Additional context
Originally brought as a CRW integration issue: https://issues.redhat.com/browse/CRW-2473

**Comment by amisevsk** [comment]
cc: @ibuziuk @l0rd this is likely a milestone 3 issue

**Comment by skabashnyuk** [comment]
in Eclipse Che we  have this https://github.com/eclipse-che/che-operator/pull/1027

**Comment by metlos** [comment]
yes, mounting of proxy settings to workspace containers should already work. This issue is about supporting that also in built-in containers, is that right? I am al little bit out of the loop on DWO capabilities, so I didn't realize project clone happens in DWO and so is affected by this, too.

**Comment by l0rd** [comment]
@metlos cloning happens in initContainers, the mechanism that works for regular containers should work for other containers too.
