### ISSUE TITLE
Add additional labels and annotations to the workspace-credentials-secret

### ISSUE THREAD

**Issue by vinokurig** [devfile/devworkspace-operator#732]
### Description

Add 
```JSON
"labels": {
   "controller.devfile.io/mount-to-devworkspace": "true",
   "controller.devfile.io/watch-secret": "true"
}, 
"annotations": {
   "controller.devfile.io/mount-path": "/etc/ssh/"
}
```
to the `workspace-credentials-secret` so that stored SSH keys will be mounted to all workspace containers.

**Comment by amisevsk** [comment]
This goes against the intended use-case for the `workspace-credentials-secret`, which is intended to store any secret data shared by workspaces (not just ssh keys) -- see: https://github.com/devfile/devworkspace-operator/pull/546. Adding these automount fields automatically could conflict with ssh configuration supplied from a different source (e.g. if the user creates their own automount SSH secret) with no way to avoid the conflict.
