### ISSUE TITLE
Need to make sure that namespace temination will not be blocked by the DevWorkspace finalizers

### ISSUE THREAD

**Issue by ibuziuk** [devfile/devworkspace-operator#738]
This scenario is particularly important for the Developer Sandbox / workspaces.openshift.com user deactivation flow. When a user is deactivated their namespace is removed. We need to make sure that DevWorkspace presence will not block the namespace removal and it will not be in the `Terminating` state forever due to finalizers:

![image](https://user-images.githubusercontent.com/1461122/149532896-574eee61-d31b-4c1a-9ea8-356ea9815f90.png)

![image](https://user-images.githubusercontent.com/1461122/149533107-08ef2b11-0953-4a69-8144-f34666dcf5da.png)

**Comment by amisevsk** [comment]
Tested deleting a few namespaces with various numbers of Workspaces both stopped and running and found no issues. Closing for now as there's not much more to be done.

**Comment by Dave-c-Ross** [comment]
Still happening :/

`status:
  conditions:
  - lastTransitionTime: "2023-10-24T02:23:06Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2023-10-24T02:23:06Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2023-10-24T02:23:06Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2023-10-24T02:23:06Z"
    message: 'Some resources are remaining: devworkspaceroutings.controller.devfile.io
      has 3 resource instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2023-10-24T02:23:06Z"
    message: 'Some content in the namespace has finalizers remaining: devworkspacerouting.controller.devfile.io
      in 3 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating
`

**Comment by amisevsk** [comment]
I believe that finalizer is being set by the Che Operator to ensure routing configurations for the workspace are properly cleaned up in the gateway container. I'll reopen the issue so that we can look into it. 

To double check, @Dave-c-Ross is the finalizer stuck for a long period (e.g. 5+ minutes)? Is the Che Operator healthy on that cluster? We might expect some delay in clearing that finalizer but it shouldn't indefinitely block namespace removal.
