### ISSUE TITLE
Make default PVC size configurable

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#740]
### Description
PVCs created by the operator by default request 1Gi of storage. The devfile API spec includes a "size" field in volume components, but it would be helpful to be able to configure the default request for creating PVCs as well.

This task is complicated by:
* It's not clear what the `size` field in a volume component means when a `common` storage type is used (e.g. all volumes for all workspaces mount the same PVC
* It's unclear how to manage PVC size in general, since most PVCs cannot be dynamically resized.

**Comment by benoitf** [comment]
even trying a custom 'projects' component with a size field didn't worked in my devfile. It was still a 1Gi PV ( from common)
