### ISSUE TITLE
Support setting annotations on services/endpoints from DevWorkspace

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#799]
### Description
With PR https://github.com/devfile/devworkspace-operator/pull/797, changes from https://github.com/devfile/api/pull/661 are now available in the DevWorkspace API. PR #797 added support for setting deployment annotations, but currently the `.spec.components[].container.annotation.service` and `.spec.components[].container.endpoints[].annotation` fields are ignored.

### Additional context
Devfile API PR introducing feature: https://github.com/devfile/api/pull/661

**Comment by AObuchow** [comment]
Can we close this in favour of https://github.com/devfile/devworkspace-operator/issues/1023?

**Comment by amisevsk** [comment]
Ah woops, didn't do a great job searching for old issues.
