### ISSUE TITLE
Allow to specify arbitrary pods fields

### ISSUE THREAD

**Issue by l0rd** [devfile/devworkspace-operator#852]
### Description

There are a few examples of workspaces Pods annotations (`openshift.io/scc` or `runtimeClassName`) or Pods spec fields (`runtimeClassName`, `schedulerName`) that users want to be able to specify. 

The approach until now has been to use `spec.template.attributes`. But that requires code/spec changes for every new field/annotation that we want to support. To avoid that, and allow users to set arbitrary Pods fields, we could add a `DevWorspace.spec.pods` field for that:

```diff
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: myspacework
spec:
  started: true
+  pods:
+    metadata:
+      annotations:
+        io.openshift.userns: "true"
+        io.kubernetes.cri-o.userns-mode: "auto:size=65536;map-to-root=true"  # <-- user namespace
+        openshift.io/scc: container-build
+    spec:
+      runtimeClassName: kata
+      schedulerName: stork      
  template:
  (...)
```

### Additional context

- https://github.com/eclipse/che/issues/21420
- https://github.com/eclipse/che/issues/21105
- https://github.com/eclipse/che/issues/20459

**Comment by amisevsk** [comment]
Opened Devfile API issue: https://github.com/devfile/api/issues/860
