### ISSUE TITLE
Icon for Dev Workspace Operator

### ISSUE THREAD

**Issue by ibuziuk** [devfile/devworkspace-operator#892]
The suggestion is to have a combination of the OLM / Operator and the Devfile:
- https://devfile.io/
- https://olm.operatorframework.io/

**Comment by l0rd** [comment]
@beaumorley I love that. My preferred is the first one. What about using the blue of the devfile logo instead of the red?

**Comment by ibuziuk** [comment]
looks, great
@beaumorley would it be possible to provide the base64 version of the first icon so we would verify how would it look when enabled on operator's csv?

**Comment by beaumorley** [comment]
@ibuziuk @l0rd I can ask Sunil to do this. I am going to Slack him in a thread with you @ibuziuk in case he has questions.

**Comment by ibuziuk** [comment]
thank you! the target for the operator with icon is 0.16.0 release

**Comment by ibuziuk** [comment]
Adding icons provided by the UX team

![Devfile_Operator (1)](https://user-images.githubusercontent.com/1461122/183942442-aa6257c2-a72d-44bd-b5dd-6ebea85d2a9c.svg)
[cb-base64-string.txt](https://github.com/devfile/devworkspace-operator/files/9301382/cb-base64-string.txt)
[cb-image-tag.txt](https://github.com/devfile/devworkspace-operator/files/9301383/cb-image-tag.txt)
[cb-bg-css.txt](https://github.com/devfile/devworkspace-operator/files/9301384/cb-bg-css.txt)
![Devfile_Operator64_64](https://user-images.githubusercontent.com/1461122/183942512-6cfea371-f743-4a33-a15e-65b68b954191.png)
m
