### ISSUE TITLE
Installation on OKD is not straight-forward (OperatorHub)

### ISSUE THREAD

**Issue by a-elie** [devfile/devworkspace-operator#894]
### Description
Is it possible to have some kind of walk-trough in the readme ?

- Default `ClusterServiceVersion` mentions `registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.xx`
In OKD, this image is not available
The installation is successfully completed using `quay.io/openshift/origin-kube-rbac-proxy:4.xx` (edited in yaml)

- `devworkspace-operator-config` have to be created in `openshift-operators` namespace
Is it possible to have a pre-filled config created automatically by the operator ?
Related : https://github.com/devfile/devworkspace-operator/issues/843

Thanks !

### Additional context
devworkspace-operator.v0.16.0-dev.7

**Comment by amisevsk** [comment]
Hi @a-elie, thanks for pointing this out. Currently, our OperatorHub install targets OpenShift and assumes image pull secrets are present (allowing pulling the `ose-kube-rbac-proxy` image). I'll look into making the process there on OKD simpler -- the two images are the same, so it's just a matter of selecting the correct one.

As for the configuration CR, on OKD it shouldn't be strictly necessary and is only required if you need to override default values. We can try to create a blank one on startup to make editing it easier though (it's tedious to have to create the object with a specific name). 

OKD was a blindspot for me until now, I agree some improved documentation is needed.

**Comment by a-elie** [comment]
> it's tedious to have to create the object with a specific name

This !

> I'll look into making the process there on OKD simpler

Thank you @amisevsk, updating is quite difficult with the current edit-by-hand process

**Comment by cgruver** [comment]
I have also encountered this issue while working with upstream Che on OKD.

Since all of the other images needed by the operator are restricted by a pull secret, why not just use `kube-rbac-proxy` from `quay.io`?    Alternatively, you could move `ose-kube-rbac-proxy:v4.xx` to a space in `registry.redhat.io/` that is not restricted by a pull secret.  Like the UBI images.

**Comment by debovema** [comment]
Having the same issue here.
@a-elie :  what did you edit to make it work with quay.io image please ?

**Comment by cgruver** [comment]
You can fix it from the CLI, or from the console.

The key is to edit the `ClusterServiceVersion` `devworkspace-operator.v0.17.0` in the `openshift-operators` namespace.

Replace `registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.xx` in the CSV with `quay.io/openshift/origin-kube-rbac-proxy:4.X.0`. where `xx` is the version that it is looking from `registry.redhat.io` and `X` is the version from `quay.io`

FWIW, I am using the version that corresponds to the OKD version that I have running.  `4.12.0` in my case.

So, my particular substitution looked like: Replace `registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.8.0` in the CSV with `quay.io/openshift/origin-kube-rbac-proxy:4.12.0`

```bash
oc edit csv devworkspace-operator.v0.17.0 -n openshift-operators
```

will open it in a `vi` editor from the CLI.

**Comment by cgruver** [comment]
@debovema 

Here you go:

Run this from a terminal as cluster admin after installing the DevWorkspace Operator

__Note:__ adjust for your particular version.

```bash
oc get csv devworkspace-operator.v0.18.0 -n openshift-operators -o yaml > dw-csv.yaml
sed -i "s|registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.8|quay.io/openshift/origin-kube-rbac-proxy:4.12.0|g" dw-csv.yaml
oc apply -f dw-csv.yaml -n open shift-operators
oc scale deployment devworkspace-webhook-server --replicas=0 -n openshift-operators
oc scale deployment devworkspace-webhook-server --replicas=1 -n openshift-operators
oc scale deployment devworkspace-controller-manager --replicas=0 -n openshift-operators
oc scale deployment devworkspace-controller-manager --replicas=1 -n openshift-operators
```

**Comment by debovema** [comment]
Thank you very much for the detailed instructions ! :+1: 
That's more or less what I tried (editing the CSV resource) but it was reverted shortly after (maybe not editing the CSV in the right namespace since it is installed in all namespaces).
Now it is working like a charm on a vanilla k8s created with kind !

**Comment by amisevsk** [comment]
Note the minor typo in those instructions:
```
oc apply -f dw-csv.yaml -n open shift-operators
```

Hopefully in the new year I'll find time to set this up for OKD

**Comment by cgruver** [comment]
Ha…  yes, the browser keeps trying to be helpful with grammar and spelling…

**Comment by amisevsk** [comment]
After verifying with a folks internally, I've opened https://github.com/devfile/devworkspace-operator/pull/1015 to update the install to use `gcr.io/kubebuilder/kube-rbac-proxy` (same as for kubernetes installs). 

For now, we're not using `quay.io/openshift/origin-kube-rbac-proxy` as I'm not clear on how this image is built or its intended use. If there's any information there (or why there are so many unresolved CVEs against recent images) then we can switch to that for consistency.

**Comment by cgruver** [comment]
The name of `quay.io/openshift/origin-kube-rbac-proxy` suggests that it's part of OKD, or was at least part of OKD.

FWIW, I think the switch to the `gcr.io` image is a good choice.

**Comment by cgruver** [comment]
Updated script to patch the dev workspace install on OKD:

```bash
DW_OP=$(oc get csv -n openshift-operators | grep devworkspace-operator | cut -d" " -f1)
oc get csv ${DW_OP} -n openshift-operators -o yaml > dw-csv.yaml
sed -i "s|registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.8|gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1|g" dw-csv.yaml
oc apply -f dw-csv.yaml -n openshift-operators
sleep 2
oc scale deployment devworkspace-webhook-server --replicas=0 -n openshift-operators
oc scale deployment devworkspace-controller-manager --replicas=0 -n openshift-operators
sleep 2
oc scale deployment devworkspace-webhook-server --replicas=1 -n openshift-operators
oc scale deployment devworkspace-controller-manager --replicas=1 -n openshift-operators
```

**Comment by cgruver** [comment]
FWIW:  Verified this is working in the `Next` channel.  `0.0.20230109-next.ad40405`
