### ISSUE TITLE
Include more context/information when a workspace fails to start due to timeout

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#903]
### Description
When a starting workspace fails to reach the running state before the `ProgressTimeout`, the workspace start is failed with message
```
devworkspace failed to progress past phase 'Starting' for longer than timeout (<duration>)
```

This message should be updated with additional information, e.g.
* The phase the workspace was in when it timed out (e.g. waiting on editors, waiting on deployment ready, etc.)
* Potential causes for the timeout, if applicable and if the operator can guess as to the cause.

**Comment by AObuchow** [comment]
Since this is similar to https://github.com/devfile/devworkspace-operator/issues/1079, I'm going to close this issue in favour of that one

**Comment by amisevsk** [comment]
:D I thought I had created an issue for this before

Thanks @AObuchow
