### ISSUE TITLE
Compute required size for per-workspace PVC when all volumes have sizes specified.

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#947]
### Description
Devfile volume components support specifying a size parameter, which is currently ignored. This means that the configured default value for PVC size is always used, even if a DevWorkspace specifies the size of all volumes. 

Instead, DWO should have a mechanism for computing PVC size from all volumes in the DevWorkspace, and use that if the request is larger than the default. This would enable supporting workspaces that require a lot of storage without increasing the default request for _all_ workspaces.

**Comment by AObuchow** [comment]
> DWO should have a mechanism for computing PVC size from all volumes in the DevWorkspace, and **use that if the request is larger than the default.**

Is it a strict requirement to use the calculated size only if it's larger than the default size? There's a tradeoff: save space if you don't need to default 5Gi, or ensure you have always headroom if the calculated size is smaller than the default. Not sure which is better.

In my mind, having headroom seems better, but it is up for debate. 

CC: @ibuziuk @l0rd

**Comment by amisevsk** [comment]
Given what we've found with per-workspace PVCs, using whatever is defined and ignoring defaults is probably the right choice. The main concern would be once-working devfiles no longer working right, but its easily remedied (request as much memory as you actually need).
