### ISSUE TITLE
Add options for configuring DevWorkspace ServiceAccount

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#962]
### Description
In some cases, it may be useful to be able to use a custom service account for DevWorkspaces instead of relying on DWO to auto-provision a service account for each DevWorkspace. We should be able to 
1. Enable specifying a service account name to be used for all DevWorkspaces
2. Disable automatic service account creation (which requires a name to be set)

**Comment by max-cx** [comment]
Sync'd with Red Hat JIRA https://issues.redhat.com/browse/CRW-3629

**Comment by max-cx** [comment]
Release note sync'd with Red Hat JIRA https://issues.redhat.com/browse/CRW-3470
