### ISSUE TITLE
Support specifying patch directives in pod and container overrides

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#966]
### Description
When using the pod-overrides or container-overrides attribute in a DevWorkspace, the override bytes are deserialized into a PodSecurityContext/SecurityContext and applied via strategic merge patch. However, this approach prevents _un-setting_ fields within a struct, as empty fields are ignored in the serialize/deserialize procedure (due to omitempty). This means that if a pod is configured to have security context

```yaml
securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
```
it's not possible to specify a pod override to make this
```yaml
securityContext:
    runAsUser: 1001
```

Kubernetes strategic merge supports patch directives to change the behavior of the patch:
* `$patch: replace` causes fields to be applied as-is rather than merged into existing values
* `$patch: delete` deletes fields altogether without patching anything

### Additional context
Originally brought up in discussion on https://github.com/devfile/api/issues/920

**Comment by l0rd** [comment]
@amisevsk is there some documentation about this or should we add it (in the [dwo additional doc md](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#pod-overrides) file I guess)?

**Comment by l0rd** [comment]
cc @max-cx

**Comment by amisevsk** [comment]
I'm hesitant to add explicit documentation as it's not our functionality so much as it's what is supported by Kubernetes strategic merge patch (documented [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md)).

**Comment by l0rd** [comment]
Right. Linking to the strategic merge path documentation and mentioning that directives modify the behavior would be useful I think.

**Comment by amisevsk** [comment]
Created PR https://github.com/devfile/devworkspace-operator/pull/981 to add a short note and link to docs mentioned above.
